In [1]:
import numpy as np

## DataTypes y Attributes

In [2]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[2,4,6,8],
              [10,12,14,16]])

a3 = np.array([[[1, 3, 5],
                [7, 9, 11],
                [13, 15, 17]],
               [[2, 4, 6],
                [8, 10, 12],
                [14, 16, 18]]])

In [5]:
a2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [6]:
a3

array([[[ 1,  3,  5],
        [ 7,  9, 11],
        [13, 15, 17]],

       [[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]]])

<img src="../../assets/section-5/anatomy-numpy-array.webp" alt="Arrays Numpy" width="600">

In [7]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [8]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('int64'), dtype('int64'))

In [9]:
a1.size, a2.size, a3.size

(3, 8, 18)

In [10]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [11]:
# Crear un DataFrame de un array de Numpy
import pandas as pd

df = pd.DataFrame(a2)
df

0   1   2   3
0   2   4   6   8
1  10  12  14  16

## Creación de Arrays

In [12]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [13]:
sample_array.dtype

dtype('int64')

In [14]:
ones = np.ones([2,3])

In [15]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
ones.dtype

dtype('float64')

In [17]:
type(ones)

numpy.ndarray

In [18]:
zeros = np.zeros((2,3))

In [19]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [21]:
random_array = np.random.randint(0, 10, size=(3,5))
random_array

array([[7, 2, 8, 8, 9],
       [4, 6, 8, 1, 4],
       [5, 2, 0, 6, 9]])

In [22]:
random_array.size

15

In [23]:
random_array.shape

(3, 5)

In [24]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.67986874, 0.17631354, 0.47970191],
       [0.23003795, 0.02114333, 0.08248634],
       [0.94641837, 0.45166586, 0.36122272],
       [0.26132657, 0.7901949 , 0.77740373],
       [0.72054438, 0.98399525, 0.05466484]])

In [25]:
random_array_2.shape

(5, 3)

In [26]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.19174896, 0.56896782, 0.48912869],
       [0.33235449, 0.12323851, 0.4374426 ],
       [0.1561047 , 0.39652439, 0.61352144],
       [0.97370238, 0.87943533, 0.36744041],
       [0.3081077 , 0.30775336, 0.63150852]])

In [27]:
np.random.seed(42) # Genera números aleatorios reproducibles
random_array_4 = np.random.randint(10, size =(5, 3))
random_array_4

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7],
       [7, 2, 5]])

## Arrays y Matrices

In [28]:
np.unique(random_array_4)

array([2, 3, 4, 5, 6, 7, 9])

In [29]:
a1

array([1, 2, 3])

In [30]:
a2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [31]:
a3

array([[[ 1,  3,  5],
        [ 7,  9, 11],
        [13, 15, 17]],

       [[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]]])

In [32]:
a1[0]

1

In [33]:
a2[0]

array([2, 4, 6, 8])

In [34]:
a3[0]

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [35]:
a3.shape

(2, 3, 3)

In [36]:
a3

array([[[ 1,  3,  5],
        [ 7,  9, 11],
        [13, 15, 17]],

       [[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]]])

In [37]:
a3[:2, :2, :2]

array([[[ 1,  3],
        [ 7,  9]],

       [[ 2,  4],
        [ 8, 10]]])

In [38]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[4, 1, 7, 5, 1],
         [4, 0, 9, 5, 8],
         [0, 9, 2, 6, 3],
         [8, 2, 4, 2, 6]],

        [[4, 8, 6, 1, 3],
         [8, 1, 9, 8, 9],
         [4, 1, 3, 6, 7],
         [2, 0, 3, 1, 7]],

        [[3, 1, 5, 5, 9],
         [3, 5, 1, 9, 1],
         [9, 3, 7, 6, 8],
         [7, 4, 1, 4, 7]]],


       [[[9, 8, 8, 0, 8],
         [6, 8, 7, 0, 7],
         [7, 2, 0, 7, 2],
         [2, 0, 4, 9, 6]],

        [[9, 8, 6, 8, 7],
         [1, 0, 6, 6, 7],
         [4, 2, 7, 5, 2],
         [0, 2, 4, 2, 0]],

        [[4, 9, 6, 6, 8],
         [9, 9, 2, 6, 0],
         [3, 3, 4, 6, 6],
         [3, 6, 2, 5, 1]]]])

In [39]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)