## Sorting arrays - Ordenación de Arrays

In [1]:
import numpy as np

In [2]:
random_array = np.random.randint(10, size=(3,5))
random_array

array([[9, 1, 2, 4, 8],
       [0, 5, 6, 1, 8],
       [7, 0, 4, 3, 8]])

In [3]:
# Ordenar los números de un array
np.sort(random_array) # devuelve una copia ordenada de una matriz (en cada eje)

array([[1, 2, 4, 8, 9],
       [0, 1, 5, 6, 8],
       [0, 3, 4, 7, 8]])

In [4]:
# Ordena los índices del array
sorted_indices = np.argsort(random_array) # devuelve los índices que ordenarían el array
sorted_indices

array([[1, 2, 3, 4, 0],
       [0, 3, 1, 2, 4],
       [1, 3, 2, 0, 4]])

In [5]:
# Podemos usar los índices para reordenar un array manualmente
a1 = np.array([1, 2, 3])

### Obtener valores máximos y mínimos

In [6]:
np.argmin(a1)

0

In [7]:
np.argmax(a1)

2

In [8]:
np.argmax(random_array, axis=0)

array([0, 1, 1, 0, 0])

- La fila 1 tiene el número más alto en la primera columna
- La fila 0 tiene el número más alto en la segunda columna
- La fila 1 tiene el número más alto en la tercera columna
- La fila 1 tiene el número más algo en la cuarta columna
- La fila 2 tiene el número más alto en la quinta columna

In [9]:
np.argmax(random_array, axis=1)

array([0, 4, 4])

- La posición 2 de la primera fila es el valor más alto de esa fila
- La posición 2 de la segunda fila es el valor más alto de esa fila
- La posición 4 de la tercera fila es el valor más alto de esa fila