## Ejercicio práctico:
#### Ventas de mantequilla de frutos secos 🥜

Calcular el total de ingresos semanal de cada tipo de mantequilla.

In [1]:
import pandas as pd
import numpy as np

In [2]:
days = ["Lun", "Mar", "Mie", "Jue", "Vie"]
butters = ["Almond butter", "Peanut butter", "Cashew butter"]
sales_amount = np.random.randint(20, size=(5, 3)) # Nº de frascos vendidos

In [3]:
sales_amount

array([[10, 16, 16],
       [19,  3,  4],
       [ 1, 18,  3],
       [ 2,  9,  6],
       [13, 14,  8]])

In [4]:
# Crear el DataFrame 'weekly_sales'
weekly_sales = pd.DataFrame(sales_amount,
                            index=days,
                            columns=butters)
weekly_sales

Almond butter  Peanut butter  Cashew butter
Lun             10             16             16
Mar             19              3              4
Mie              1             18              3
Jue              2              9              6
Vie             13             14              8

In [5]:
prices = np.array([15, 12, 18])  # Precio de cada frasco
prices

array([15, 12, 18])

In [6]:
prices.shape

(3,)

In [7]:
# Crear el DataFrame 'butter_prices'
butter_prices = pd.DataFrame(prices.reshape(1,3),
                           index=["Price"],
                           columns=butters)
butter_prices

Almond butter  Peanut butter  Cashew butter
Price             15             12             18

In [8]:
total_sales = np.dot(weekly_sales, butter_prices.T)
total_sales

array([[630],
       [393],
       [285],
       [246],
       [507]])

In [9]:
weekly_sales["Total"] = total_sales
weekly_sales

Almond butter  Peanut butter  Cashew butter  Total
Lun             10             16             16    630
Mar             19              3              4    393
Mie              1             18              3    285
Jue              2              9              6    246
Vie             13             14              8    507