In [1]:
import numpy as np

In [2]:
a1 = np.array([1, 2, 3])
a2 = np.array([[1., 2., 3.3],
               [4., 5., 6.5]])

## Operadores de comparación

### Comparaciones básicas

In [3]:
a1, a2

(array([1, 2, 3]),
 array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]))

In [4]:
a1 > a2 # Comparar elementos entre dos arrays

array([[False, False, False],
       [False, False, False]])

In [5]:
bool_array = a1 >= a2
bool_array

array([[ True,  True, False],
       [False, False, False]])

In [6]:
type(bool_array), bool_array.dtype

(numpy.ndarray, dtype('bool'))

In [7]:
a1 > 5 # Comparar si los elementos de un array cumplen una condición

array([False, False, False])

In [8]:
a1 == a2 # Comparar elementos entre dos arrays

array([[ True,  True, False],
       [False, False, False]])

### Aplicaciones prácticas

In [9]:
# Filtrar datos en un array
filtered = a2[a2 > 2] # Extraer elementos que cumplan ciertas condiciones
filtered

array([3.3, 4. , 5. , 6.5])

In [10]:
# Comparaciones múltiples
result = (a2 > 2) & (a2 < 6) # Combina múltiples condiciones usando operadores lógicos
result

array([[False, False,  True],
       [ True,  True, False]])

In [11]:
# Comparar si todos o algún elemento cumple una condición:
print(np.all(a2 > 3)) # verifica si todos los elementos cumplen una condición
print(np.any(a2 > 3)) # verifica si algún elemento cumplen una condición

False
True


> **Notas clave**
> - El resultado de las comparaciones es un array booleano del mismo tamaño que el array original.
> - Los operadores (`>`, `<`, `>=`, `<=`, `==`, `!=`) funcionan de manera nativa con arrays de NumPy.