## Pasar imágenes a Arrays de NumPy

<img src="../../assets/section-5/panda.jpg" width=600>

In [1]:
# Pasar una imagen a un array de NumPy
from matplotlib.image import imread

panda = imread("../../assets/section-5/panda.jpg")

In [2]:
type(panda)

numpy.ndarray

In [3]:
panda.size, panda.shape, panda.ndim

(1020600, (486, 700, 3), 3)

Cuando la imagen se carga con `imread`, se convierte en un array 3D donde:
- El primer eje representa las filas (alto de la imagen).
- El segundo eje representa las columnas (ancho de la imagen).
- El tercer eje representa los canales de color (por ejemplo, RGB con 3 canales).

In [4]:
panda[:4]

array([[[111, 122,  80],
        [112, 123,  81],
        [112, 123,  81],
        ...,
        [128, 146,  96],
        [127, 145,  93],
        [126, 145,  90]],

       [[110, 123,  80],
        [110, 123,  80],
        [110, 123,  80],
        ...,
        [128, 146,  96],
        [127, 145,  93],
        [126, 144,  92]],

       [[112, 125,  81],
        [112, 125,  81],
        [109, 125,  80],
        ...,
        [129, 147,  97],
        [128, 146,  96],
        [127, 145,  93]],

       [[115, 131,  84],
        [114, 130,  83],
        [112, 130,  82],
        ...,
        [131, 149, 101],
        [130, 148,  98],
        [129, 147,  97]]], dtype=uint8)

#### Probamos con otra imagen

<img src="../../assets/section-5/mango.jpg" width=600>

In [5]:
mango = imread("../../assets/section-5/mango.jpg")

In [6]:
mango.size, mango.shape, mango.ndim

(136323072, (5504, 8256, 3), 3)

In [7]:
mango[:2]

array([[[123, 117, 121],
        [126, 120, 120],
        [126, 121, 117],
        ...,
        [138, 139, 134],
        [138, 139, 134],
        [138, 139, 133]],

       [[122, 120, 121],
        [125, 121, 120],
        [123, 119, 116],
        ...,
        [140, 141, 136],
        [140, 141, 136],
        [139, 140, 135]]], dtype=uint8)

In [8]:
mango[0, 0] # Valor del píxel en la esquina superior izquierda

array([123, 117, 121], dtype=uint8)

In [9]:
mango[2, 3]

array([121, 120, 118], dtype=uint8)