# NumPy Practice

Este cuaderno ofrece un conjunto de ejercicios para diferentes tareas con NumPy.

Cabe destacar que puede haber más de una forma diferente de responder a una pregunta o completar un ejercicio.

Para más referencias y recursos, se recomienda consultar la [documentación de NumPy](https://numpy.org/devdocs/user/index.html).

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([2, 4, 6, 8])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[2, 14, 6, 18],
               [12, 4, 16, 8]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.random.randint(20, size=(2, 3, 4))

In [3]:
a1, a2, a3

(array([2, 4, 6, 8]),
 array([[ 2, 14,  6, 18],
        [12,  4, 16,  8]]),
 array([[[14, 16,  3,  2],
         [15,  3, 12,  1],
         [15,  9,  4, 13]],
 
        [[ 8, 13,  5,  4],
         [ 1, 15, 18, 18],
         [12, 14, 13, 18]]]))

Ahora que has creado 3 arrays diferentes, vamos a ver detalles sobre ellos.

Muestra la forma, el número de dimensiones, el tipo de dato, el tamaño y el tipo de cada array.

In [4]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.ndim, a1.shape, a1.size, a1.dtype

(1, (4,), 4, dtype('int64'))

In [5]:
# Attributes of 2-dimensional array
a2.ndim, a2.shape, a2.size, a2.dtype

(2, (2, 4), 8, dtype('int64'))

In [6]:
# Attributes of 3-dimensional array
a3.ndim, a3.shape, a3.size, a3.dtype

(3, (2, 3, 4), 24, dtype('int64'))

In [7]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

df = pd.DataFrame(a2)
df

0   1   2   3
0   2  14   6  18
1  12   4  16   8

In [8]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [10]:
# Create an array within a range of 0 and 100 with step 3
a4 = np.arange(0, 100, 3)
a4

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [11]:
a4.size, a4.shape, a4.ndim

(34, (34,), 1)

In [12]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
a5 = np.random.randint(0, 10, size=(7, 2))
a5

array([[1, 6],
       [4, 4],
       [5, 8],
       [9, 2],
       [8, 6],
       [7, 2],
       [2, 6]])

In [13]:
a5.size, a5.shape, a5.ndim

(14, (7, 2), 2)

In [14]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
a6 = np.random.rand(3, 5)
a6

array([[0.17541225, 0.77083915, 0.77949859, 0.19438864, 0.47745441],
       [0.00804455, 0.08295709, 0.50140298, 0.85728371, 0.83549572],
       [0.9247058 , 0.28150355, 0.44342799, 0.46830065, 0.36280056]])

In [15]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_arr = np.random.randint(10, size=(4, 6))
random_arr

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Ejecuta la celda de arriba nuevamente, ¿qué pasa?

¿Los números en el array son diferentes o iguales? ¿Por qué crees que es así?

***El uso de `random.seed()` asegura reproducibilidad en las operaciones aleatorias.***

In [16]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
a7 = np.random.randint(1, 10, size=(3, 7))

# Find the unique numbers in the array you just created
np.unique(a7)

array([1, 2, 3, 4, 5, 7, 9])

In [17]:
a7

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2],
       [4, 9, 2, 9, 5, 2, 4]])

In [18]:
# Find the 0'th index of the latest array you created
a7[0]

array([9, 1, 3, 7, 4, 9, 3])

In [19]:
# Get the first 2 rows of latest array you created
a7[0:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [20]:
# Get the first 2 values of the first 2 rows of the latest array
a7[0:2, 0:2]

array([[9, 1],
       [5, 3]])

In [21]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
a8 = np.random.randint(10, size=(3, 5))
a9 = np.ones((3,5))

In [22]:
a8

array([[6, 7, 2, 0, 3],
       [1, 7, 3, 1, 5],
       [5, 9, 3, 5, 1]])

In [23]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
# Add the two arrays together
a8 + a9

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [25]:
# Create another array of ones of shape (5, 3)
a10 = np.ones((5, 3))
a10

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
# Try add the array of ones and the other most recent array together
# a8 + a9 + a10

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

Cuando ejecutas la última celda, aparece un error. ¿Por qué crees que es esto?

¿Cómo lo repararías?

In [27]:
arr_sum = a8 + a9 + a10.T
arr_sum

array([[ 8.,  9.,  4.,  2.,  5.],
       [ 3.,  9.,  5.,  3.,  7.],
       [ 7., 11.,  5.,  7.,  3.]])

In [28]:
# Create another array of ones of shape (3, 5)
ones = np.ones((3, 5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
# Subtract the new array of ones from the other most recent array
arr_sum - ones

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [30]:
# Multiply the ones array with the latest array
ones * arr_sum

array([[ 8.,  9.,  4.,  2.,  5.],
       [ 3.,  9.,  5.,  3.,  7.],
       [ 7., 11.,  5.,  7.,  3.]])

In [31]:
# Take the latest array to the power of 2 using '**'
arr_sum ** 2

array([[ 64.,  81.,  16.,   4.,  25.],
       [  9.,  81.,  25.,   9.,  49.],
       [ 49., 121.,  25.,  49.,   9.]])

In [32]:
# Do the same thing with np.square()
np.square(arr_sum)

array([[ 64.,  81.,  16.,   4.,  25.],
       [  9.,  81.,  25.,   9.,  49.],
       [ 49., 121.,  25.,  49.,   9.]])

In [33]:
# Find the mean of the latest array using np.mean()
np.mean(arr_sum)

5.866666666666666

In [34]:
# Find the maximum of the latest array using np.max()
np.max(arr_sum)

11.0

In [35]:
# Find the minimum of the latest array using np.min()
np.min(arr_sum)

2.0

In [36]:
# Find the standard deviation of the latest array
np.std(arr_sum)

2.578543947441829

In [37]:
# Find the variance of the latest array
np.var(arr_sum)

6.648888888888889

In [38]:
# Reshape the latest array to (3, 5, 1)
arr_reshape = arr_sum.reshape(3, 5, 1)
arr_reshape

array([[[ 8.],
        [ 9.],
        [ 4.],
        [ 2.],
        [ 5.]],

       [[ 3.],
        [ 9.],
        [ 5.],
        [ 3.],
        [ 7.]],

       [[ 7.],
        [11.],
        [ 5.],
        [ 7.],
        [ 3.]]])

In [39]:
# Transpose the latest array
arr_reshape.T

array([[[ 8.,  3.,  7.],
        [ 9.,  9., 11.],
        [ 4.,  5.,  5.],
        [ 2.,  3.,  7.],
        [ 5.,  7.,  3.]]])

¿Qué hace la transposición?

In [40]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
random_arr = np.random.randint(10, size=(3, 3))
random_arr_2 = np.random.randint(10, size=(3, 2))

In [41]:
# Perform a dot product on the two newest arrays you created
np.dot(random_arr, random_arr_2)

array([[ 88, 117],
       [100, 123],
       [ 89, 127]])

In [42]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
random_arr = np.random.randint(10, size=(4, 3))
random_arr_2 = np.random.randint(10, size=(4, 3))

In [43]:
# Perform a dot product on the two newest arrays you created
np.dot(random_arr, random_arr_2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

No funciona. ¿Cómo lo arreglarías?

In [44]:
np.dot(random_arr, random_arr_2.T)

array([[ 24, 102,  96,   8],
       [ 16, 114, 106,  63],
       [ 22, 123, 114,  56],
       [  8,  60,  58,   7]])

Observa cómo realizar una transposición permite que ocurra el producto punto.

¿Por qué es esto?

Revisar la documentación sobre [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) puede ayudar, así como leer la [guía de Math is Fun sobre el producto punto](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Ahora comparemos arrays.

In [45]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
random_arr = np.random.randint(10, size=(4, 3))
random_arr_2 = np.random.randint(10, size=(4, 3))

In [46]:
random_arr

array([[6, 6, 7],
       [4, 2, 7],
       [5, 2, 0],
       [2, 4, 2]])

In [47]:
random_arr_2

array([[0, 4, 9],
       [6, 6, 8],
       [9, 9, 2],
       [6, 0, 3]])

In [48]:
# Compare the two arrays with '>'
random_arr > random_arr_2

array([[ True,  True, False],
       [False, False, False],
       [False, False, False],
       [False,  True, False]])

¿Qué sucede cuando comparas los arreglos con `>`?

In [49]:
# Compare the two arrays with '>='
random_arr >= random_arr_2

array([[ True,  True, False],
       [False, False, False],
       [False, False, False],
       [False,  True, False]])

In [50]:
# Find which elements of the first array are greater than 7
random_arr > 7

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [51]:
# Which parts of each array are equal? (try using '==')
random_arr == random_arr_2

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [52]:
# Sort one of the arrays you just created in ascending order
np.sort(random_arr)

array([[6, 6, 7],
       [2, 4, 7],
       [0, 2, 5],
       [2, 2, 4]])

In [53]:
# Sort the indexes of one of the arrays you just created
np.argsort(random_arr) 

array([[0, 1, 2],
       [1, 0, 2],
       [2, 1, 0],
       [0, 2, 1]])

In [54]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(random_arr)

2

In [55]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(random_arr)

8

In [56]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(random_arr, axis=1)

array([2, 2, 0, 1])

In [57]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(random_arr, axis=0)

array([3, 1, 2])

In [58]:
# Create an array of normally distributed random numbers
np.random.randn(3, 5)

array([[ 1.79428084,  0.58068954,  0.29765045, -1.02811577, -1.41859646],
       [ 0.19033698,  0.13575383,  0.60808966,  0.70498131,  0.36092338],
       [-1.46696789,  0.89262947, -0.10525713, -0.95534644, -0.41476463]])

In [59]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensiones

Para más ejercicios, consulta el [tutorial de inicio rápido de NumPy](https://numpy.org/doc/stable/user/quickstart.html). Una buena práctica sería leerlo y, para las partes que encuentres interesantes, añadirlas al final de este cuaderno.

Presta especial atención a la sección sobre el broadcasting. Y lo más importante, trabaja con el código tanto como sea posible. Si tienes dudas, ejecuta el código y observa qué hace.

El siguiente lugar al que podrías ir es la [página de Stack Overflow para las principales preguntas y respuestas sobre NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). A menudo, encontrarás algunas de las funciones de NumPy más comunes y útiles aquí. ¡No olvides jugar con los filtros! Probablemente encontrarás algo útil aquí.

Finalmente, como siempre, recuerda que la mejor manera de aprender algo nuevo es intentarlo. Y hazlo de manera incansable. Si te interesa algún tipo de función de NumPy, preguntándote "¿Me pregunto si NumPy podría hacer eso?", ve y descúbrelo.